# Generated by Django 5.2.1 on 2025-08-19 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "orders",
            "0006_rename_orders_paym_provider_ref_idx_orders_paym_provide_95adf4_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("card", "Card"), ("mpesa", "M-Pesa")], max_length=20
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("paystack", "Paystack"),
                            ("mpesa", "M-Pesa"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("duplicate_success", "Duplicate Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("reference", models.CharField(max_length=64, unique=True)),
                (
                    "gateway_reference",
                    models.CharField(blank=True, max_length=128, null=True, unique=True),
                ),
                ("callback_received", models.BooleanField(default=False)),
                ("signature_valid", models.BooleanField(default=False)),
                ("verified", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_event", models.JSONField(blank=True, default=dict)),
                (
                    "refund_reference",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("refunded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=64)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("message", models.TextField(blank=True, default="")),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="payments.transaction",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["order"], name="payments_tr_order_i_77e900_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["user"], name="payments_tr_user_id_cee526_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["status"], name="payments_tr_status_96e6c0_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["created_at"], name="payments_tr_created_02ae92_idx"),
        ),
        migrations.AddConstraint(
            model_name="transaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "success")),
                fields=("order",),
                name="unique_success_per_order",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["event", "created_at"], name="payments_au_event_9088de_idx"),
        ),
    ]
