# Generated by Django 5.2.1 on 2025-05-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cart_cartitem'),
    ]

    operations = [
    ]
