# Generated by Django 5.2.1 on 2025-08-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_vendorapplication_vendorstaff"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorapplication",
            name="document",
            field=models.FileField(blank=True, upload_to="kyc/"),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="kra_pin",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="vendorapplication",
            name="national_id",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
