# Generated by Django 5.2.1 on 2026-03-12 10:47

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_user_role_and_backfill"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", users.models.CustomUserManager()),
            ],
        ),
    ]
