# Generated by Django 5.2.1 on 2025-08-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0002_warehouse_wh_lat_range_warehouse_wh_lng_range_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="warehouse",
            name="wh_lat_range",
        ),
        migrations.RemoveConstraint(
            model_name="warehouse",
            name="wh_lng_range",
        ),
        migrations.RemoveConstraint(
            model_name="warehouse",
            name="wh_in_kenya_bbox",
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.CheckConstraint(
                condition=models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                name="warehouse_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.CheckConstraint(
                condition=models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                name="warehouse_lng_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="warehouse",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__gte", -4.8),
                    ("latitude__lte", 5.3),
                    ("longitude__gte", 33.5),
                    ("longitude__lte", 42.2),
                ),
                name="warehouse_in_kenya_bbox",
            ),
        ),
    ]
