# Generated by Django 5.2.1 on 2025-08-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product_app", "0003_productstock_qty_check"),
    ]

    operations = [
        migrations.AddField(
            model_name="warehouse",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
