# Generated by Django 5.2.1 on 2025-09-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product_app", "0004_warehouse_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="product_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
