# Generated by Django 5.2.1 on 2025-09-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_owner_i_787833_idx',
            old_name='core_audit_owner_i_1b77a5_idx',
        ),
    ]
