# Generated by Django 5.2.1 on 2025-05-27 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_product_cartitem_user'),
    ]

    operations = [
    ]
