# Generated by Django 5.2.1 on 2025-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_is_selected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
    ]
