# Generated by Django 5.2.1 on 2025-09-25 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0008_alter_cartitem_product_and_more"),
    ]

    operations = []
