# Generated by Django 5.2.1 on 2025-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vendor_app", "0003_vendorprofile_org_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendororg",
            name="org_commission_rate",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="vendororg",
            name="org_payout_channel",
            field=models.CharField(
                choices=[("mpesa", "M-PESA"), ("bank", "Bank")],
                default="mpesa",
                max_length=16,
            ),
        ),
    ]
