# Generated by Django 5.2.1 on 2025-09-11 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_vendororg_org_commission_rate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororg',
            name='kra_pin',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AddField(
            model_name='vendororg',
            name='tax_registered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendororg',
            name='tax_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('verified', 'Verified'), ('blocked', 'Blocked')], default='unknown', max_length=16),
        ),
        migrations.CreateModel(
            name='VendorOrgAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_org_audit_entries', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='vendor_app.vendororg')),
            ],
            options={
                'verbose_name': 'Vendor Org Audit Entry',
                'verbose_name_plural': 'Vendor Org Audit Entries',
                'indexes': [models.Index(fields=['org', 'created_at'], name='vendororg_audit_idx')],
            },
        ),
    ]
