
# Generated by Django 5.2.1 on 2025-08-07 10:28


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [

        ("orders", "0001_initial"),

        ('orders', '0001_initial'),

    ]

    operations = [
        migrations.AddField
            model_name="transaction",
            name="verified",

            model_name='transaction',
            name='verified',

            field=models.BooleanField(default=False),
        ),
    ]
