# Generated by Django 5.2.1 on 2025-08-09 12:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dest_address_text",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="dest_lat",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="dest_lng",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="dest_source",
            field=models.CharField(default="autocomplete", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("dest_lat__gte", -90), ("dest_lat__lte", 90)),
                name="order_dest_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("dest_lng__gte", -180), ("dest_lng__lte", 180)),
                name="order_dest_lng_range",
            ),
        ),
    ]
