# Generated by Django 5.2.1 on 2025-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
