# Generated by Django 5.2.1 on 2025-08-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_location_address"),
        ("product_app", "0002_warehouse_remove_product_stock_productstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product_app.warehouse",
            ),
        ),
    ]
