# Generated by Django 5.2.1 on 2025-08-08 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_coords_and_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("dispatched", "Dispatched"),
                    ("en_route", "En route"),
                    ("delivered", "Delivered"),
                ],
                default="created",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    ("latitude__isnull", True),
                    _connector="OR",
                ),
                name="order_lat_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    ("longitude__isnull", True),
                    _connector="OR",
                ),
                name="order_lng_range",
            ),
        ),
    ]
