# Generated by Django 5.2.1 on 2025-08-12 13:22

from decimal import Decimal

import django.core.validators
from django.conf import settings
from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_delivery_and_money_math"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="delivery",
            new_name="orders_deli_order_i_2374e2_idx",
            old_name="delivery_order_status_idx",
        ),
        migrations.RenameIndex(
            model_name="delivery",
            new_name="orders_deli_driver__adb7af_idx",
            old_name="delivery_driver_status_idx",
        ),
        migrations.RenameIndex(
            model_name="orderitem",
            new_name="orders_orde_order_i_52f79a_idx",
            old_name="orderitem_order_product_idx",
        ),
        migrations.AlterField(
            model_name="delivery",
            name="channel_key",
            field=models.CharField(
                default=orders.models.channel_key_default,
                editable=False,
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddIndex(
            model_name="delivery",
            index=models.Index(fields=["last_ping_at"], name="orders_deli_last_pi_225781_idx"),
        ),
    ]
