# Generated by Django 5.2.1 on 2025-08-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_order_stock_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_version",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
