# Generated by Django 5.2.1 on 2025-09-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_remove_delivery_delivery_dest_lat_range_and_more"),
    ]

    operations = []
