# Generated by Django 5.2.1 on 2025-09-04 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_fix_lat_lng_before_constraint'),
        ('orders', '0009_deliveryevent'),
    ]

    operations = [
    ]
