# Generated by Django 5.2.1 on 2025-09-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_merge_20250905_0024"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="product_version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
