# Generated by Django 5.2.1 on 2025-09-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_orderitem_product_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="body_sha256",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA256 of the raw webhook body for idempotency",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
    ]
