name: CI

on:
  push:
    branches: [main, development]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5

    env:
      DJANGO_SETTINGS_MODULE: Rahim_Online_ClothesStore.settings
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/testdb
      SECRET_KEY: ${{ secrets.SECRET_KEY || 'dummy-key-for-testing' }}
      DEBUG: 0
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pre-commit
          key: ${{ runner.os }}-python-${{ hashFiles('requirements.txt', 'pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-python-

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-django pytest-cov pre-commit ruff black isort mypy

      - name: Wait for PostgreSQL
        run: |
          for i in {1..30}; do
            if pg_isready -h localhost -p 5432 -U postgres; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting for PostgreSQL... attempt $i"
            sleep 2
          done

      - name: Run database migrations
        run: python manage.py migrate --noinput

      - name: Run pre-commit checks
        run: |
          pre-commit run --all-files || true

      - name: Lint with Ruff
        run: |
          ruff check .
          ruff format --check .

      - name: Type checking with MyPy
        run: mypy .

      - name: Run tests with coverage
        run: |
          pytest -v --disable-warnings --cov=. --cov-report=term-missing --cov-report=xml

      - name: Complexity analysis
        run: |
          pip install radon xenon
          radon cc -s -a .
          xenon . --max-absolute B --max-modules B --max-average A || true

      - name: Security scan
        run: |
          pip install bandit
          bandit -r . -f html -o bandit-report.html || true

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            .coverage

      - name: Upload security report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-reports
          path: |
            bandit-report.html

      - name: Upload to Codecov (optional)
        uses: codecov/codecov-action@v3
        if: success()
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella

  quality-gate:
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Check test results
        run: |
          echo "Quality gate check passed"
          echo "Test job status: ${{ needs.test.result }}"
